import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
const base=process.argv[2]||'http://localhost:3100';
const env=parseEnv(readFileSync('.env.production.local','utf8'));const account=JSON.parse(readFileSync('.local/provisioned-user.json','utf8'));
for(const path of ['/api/comercial/leads','/api/documentos','/api/diagnosticos/demo/pdf'])assert.equal((await fetch(base+path)).status,401,path);
assert.equal((await fetch(base+'/diagnostico',{redirect:'manual'})).status,307);
assert.equal((await fetch(base+'/api/documentos',{headers:{cookie:'fs.session_token=forged'}})).status,401);
const signup=await fetch(base+'/api/auth/sign-up/email',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({name:'Blocked signup',email:'not-allowed@example.test',password:'not-a-real-password'})});assert.equal(signup.ok,false);
const login=await fetch(base+'/api/auth/sign-in/email',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({email:account.email,password:account.password})});assert.equal(login.status,200);
const set=login.headers.getSetCookie();assert.ok(set.some(v=>/httponly/i.test(v)));if(base.startsWith('https:'))assert.ok(set.some(v=>/secure/i.test(v)));
const cookie=set.map(v=>v.split(';')[0]).join('; '),headers={cookie};
const library=await fetch(base+'/api/documentos',{headers});assert.equal(library.status,200);const data=await library.json();assert.ok(data.documents.length>0);
const pdf=await fetch(base+'/api/documentos/'+data.documents[0].id,{headers});assert.equal(pdf.status,200);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,5).toString(),'%PDF-');
const manifest=await (await fetch(base+'/manifest.webmanifest')).json();assert.equal(manifest.start_url,'/diagnostico');assert.equal(manifest.display,'standalone');
const machine={authorization:`Bearer ${env.FS_AGENT_SERVICE_TOKEN}`,'x-fs-requester-phone':env.FS_AGENT_ALLOWED_PHONES.split(',')[0]};
const search=await fetch(base+'/api/agent/documents?q=11222333000181',{headers:machine});assert.equal(search.status,200);const match=await search.json();assert.ok(match.documents.length>0);
assert.equal((await fetch(base+'/api/agent/documents?q=11222333000181',{headers:{...machine,'x-fs-requester-phone':'5562000000000'}})).status,401);
const document=await fetch(base+'/api/agent/documents/'+match.documents[0].id,{headers:machine});assert.equal(document.status,200);
const logout=await fetch(base+'/api/auth/sign-out',{method:'POST',headers:{cookie,Origin:base,'Content-Type':'application/json'},body:'{}'});assert.equal(logout.status,200);
assert.equal((await fetch(base+'/api/documentos',{headers})).status,401);
console.log('PASS: login, sessão, logout/revogação, APIs/PDFs privados, cadastro fechado, PWA, busca autenticada do agente e bloqueio de número não autorizado.');
