import { validateReport } from "./model";
const totals = [68000, 54000, 43000, 36000, 28000, 21000, 16000, 12400, 8000];
export const demoReport = validateReport({
  id: "FS-DEMO-2026-001", version: 2, mode: "demo",
  company: { name: "Empresa demonstrativa Ltda.", cnpj: "12345678000195", regime: "Não verificado neste exemplo" },
  generatedAt: "2026-09-15T15:00:00.000Z",
  scope: "Cenário demonstrativo. Valores e inscrições fictícios para apresentação do sistema; não houve consulta à Receita Federal ou à PGFN. Este documento não é um parecer sobre uma empresa real.",
  summary: "O cenário ilustra R$ 339.680,00 em débitos, distribuídos entre R$ 286.400,00 em dívida ativa e R$ 53.280,00 na Receita Federal. As nove inscrições PGFN representam 84,3% do total. A conclusão sobre regularização depende da capacidade de pagamento, das condições de negociação e da análise dos documentos de cada empresa.",
  debts: [
    ...totals.map((value, i) => ({ id: `DEMO-PGFN-${String(i + 1).padStart(3, "0")}`, origin: "PGFN", tax: ["COFINS", "IRPJ", "CSLL", "PIS", "Simples Nacional"][i % 5], period: `202${3 + i % 2}`, status: i < 3 ? "Ajuizada" : i < 6 ? "Em cobrança" : "Em negociação", administrativeProcess: `DEMO-ADM-${i + 1}`, judicialProcess: i < 3 ? "Referência judicial demonstrativa" : null, registeredAt: "15/01/2025", principal: value * 70, fine: value * 10, interest: value * 15, charges: value * 5, total: value * 100, sourceId: "pgfn" })),
    ...[24500, 18900, 9880].map((value, i) => ({ id: `DEMO-RFB-${i + 1}`, origin: "RFB", tax: ["IRPJ", "CSLL", "COFINS"][i], period: "2025", status: "Pendente de regularização", administrativeProcess: null, judicialProcess: null, registeredAt: null, principal: null, fine: null, interest: null, charges: null, total: value * 100, sourceId: "rfb" })),
  ],
  sources: [
    { id: "rfb", title: "Situação fiscal - Receita Federal", provider: "Exemplo SITFIS", collectedAt: "2026-09-15T15:00:00.000Z", status: "demonstrativo", note: "Dados fictícios. O PDF oficial será vinculado após a integração real." },
    { id: "pgfn", title: "Inscrições em dívida ativa - PGFN", provider: "Exemplo PGFN", collectedAt: "2026-09-15T15:00:00.000Z", status: "demonstrativo", note: "Nove registros fictícios. A composição dos valores serve apenas para demonstrar a apresentação." },
    { id: "capag", title: "Capacidade de pagamento e negociações", provider: "Documentação complementar", collectedAt: "2026-09-15T15:00:00.000Z", status: "demonstrativo", note: "CAPAG e faturamento fictícios, exclusivamente para visualizar os indicadores do template." },
  ],
  capag: { rating: "B (ilustrativo)", amount: 60000000, note: "Capacidade e classificação fictícias. A revisão para C/D e os benefícios exibidos são hipóteses de simulação; não há enquadramento confirmado." },
  opinion: {
    scenario: { label: "Hipótese de revisão para C/D", status: "illustrative", evidence: "Parâmetros de demonstração do template: 100% dos acréscimos, limitados a 65% de cada inscrição; entrada de 6%. Não representam oferta ou modalidade disponível ao contribuinte.", targetRating: "C/D (hipótese)", chargesDiscountBps: 10000, totalDiscountCapBps: 6500, entryBps: 600, entryMonths: 12, balanceMonths: 133, conventionalMonths: 60, alternativeEntryMonths: 6, alternativeBalanceMonths: 114 },
    capagDebtBasis: 33968000, capagBasisNote: "Base fictícia na mesma data dos débitos deste exemplo. Na análise real, preservar a data e o total próprios do extrato CAPAG.",
    annualRevenue: 240000000, revenuePeriod: "2025 · faturamento fictício",
    deadline: null, releaseDate: null,
    windowNote: "Prazo de adesão e data de liberação não informados. Não é possível afirmar existência de janela disponível nem transportar a data de setembro do parecer da GPA para este caso.",
    rescissionNote: "Histórico de acordos e datas de rescisão não recebido. Identificar a natureza de cada negociação, a data da rescisão e o fundamento do eventual impedimento antes de definir a estratégia.",
    judicialNote: "Três inscrições fictícias têm referência judicial, somando R$ 165.000,00. Não foram fornecidos autos, garantias, penhoras ou decisões. A referência processual isolada não prova que a dívida esteja garantida.",
    certificateNote: "O levantamento contém também R$ 53.280,00 na Receita Federal. A análise de regularidade deve abranger ambas as origens e a situação dos créditos. Nenhuma certidão foi consultada ou emitida neste exemplo.",
    capagReview: "No cenário ilustrativo, a capacidade em 60 meses é superior ao passivo informado. Para avaliar revisão, reunir balanço, DRE, balancete, endividamento, contratos, margem operacional e fluxo de caixa projetado. O faturamento isolado não descreve a disponibilidade de caixa. A classificação-alvo exige decisão da autoridade competente e confirmação dos requisitos da modalidade.",
    legalBasis: [
      { title: "Transação tributária e descontos", application: "Identificar legislação, regulamento e modalidade aplicáveis, limites por natureza do débito e vedação de redução do principal.", status: "Referência normativa pendente de validação técnica" },
      { title: "Edital e capacidade de pagamento", application: "Conferir edital vigente, classificação, prazo, porte, data de inscrição e eventual impedimento.", status: "Edital não definido neste exemplo" },
      { title: "Certidão e garantia judicial", application: "Conferir requisitos da certidão pretendida, situação da execução, suficiência das garantias e entendimento aplicável ao caso.", status: "Análise dos autos pendente" },
    ],
    actions: [
      { action: "Conciliar relatórios da Receita Federal, PGFN e CAPAG por data e origem.", timing: "Antes da análise definitiva" },
      { action: "Obter histórico de acordos e verificar rescisões e impedimentos.", timing: "Antes de escolher modalidade" },
      { action: "Conferir a janela de adesão, o porte e os requisitos do edital.", timing: "Antes de qualquer proposta" },
      { action: "Avaliar as pendências da Receita Federal e seus efeitos na certidão.", timing: "Em paralelo" },
      { action: "Reunir documentos financeiros para eventual revisão da CAPAG.", timing: "Após validação documental" },
      { action: "Conferir processos e garantias e dimensionar eventual medida judicial.", timing: "Com a equipe jurídica" },
      { action: "Comparar desembolso, margem disponível e cenários de regularização.", timing: "Antes da decisão do cliente" },
      { action: "Validar o parecer e registrar os documentos que sustentam cada conclusão.", timing: "Antes de emitir ao cliente" },
      { action: "Monitorar negociações, pagamentos e situação processual.", timing: "Após implementação" },
    ],
    caveats: ["Todos os dados financeiros e registros desta versão são fictícios.", "Desconto, classificação-alvo e prazos são parâmetros de simulação, sem elegibilidade confirmada.", "A simulação cobre somente inscrições PGFN; o saldo da Receita Federal permanece separado.", "Os cálculos são nominais, sem atualização, juros futuros, honorários ou encargos adicionais.", "Pagamento mensal é dividido em centavos com ajuste na última parcela de cada fase.", "Percentuais de faturamento não representam garantia aceita nem direito automático à certidão.", "Dados ausentes são mantidos como não informados e nunca equivalem a saldo zero."],
    conclusion: "O cenário demonstrativo reúne R$ 286.400,00 na PGFN em nove inscrições e R$ 53.280,00 na Receita Federal, totalizando R$ 339.680,00. A composição PGFN contém R$ 200.480,00 de principal e R$ 85.920,00 de acréscimos. Na hipótese exclusivamente ilustrativa de redução integral dos acréscimos, respeitado o limite parametrizado por inscrição, a economia seria de 30% e o saldo PGFN seria de R$ 200.480,00. Esse cenário não está contratado, aprovado ou disponível por simples solicitação. A classificação ilustrativa B e a capacidade simulada exigem análise documental antes de qualquer proposta de revisão. Prazos, impedimentos e elegibilidade permanecem não confirmados. Para a frente de certidão, é necessário analisar os débitos de ambas as origens e os autos judiciais, sem presumir suficiência de eventual penhora. A recomendação é concluir a coleta, conciliar as fontes, validar as premissas econômicas e submeter o parecer à revisão técnica da FS antes da emissão definitiva.",
  },
  sections: [
    { id: "impedimentos", title: "Prazos, impedimentos e elegibilidade", content: "Não há comprovação de datas de rescisão, impedimentos vigentes ou edital aplicável. Antes de indicar uma modalidade, é necessário conferir esses elementos nos documentos oficiais. Nenhum prazo de adesão foi presumido." },
    { id: "rfb", title: "Situação fiscal na Receita Federal", content: "O exemplo contém três pendências na Receita Federal. A composição entre principal e acréscimos não foi informada e permanece em aberto. Em uma consulta real, cada débito deverá ser vinculado à data de emissão e ao relatório que o comprova." },
    { id: "pgfn", title: "Inscrições e cobrança na PGFN", content: "As nove inscrições deste cenário são demonstrativas, com situações de cobrança distintas. O total é calculado pela soma dos registros. Referências processuais não comprovam, por si sós, existência ou ausência de penhora, garantia ou decisão judicial." },
    { id: "capag", title: "Capacidade de pagamento e revisão", content: "A análise de revisão exige o relatório de capacidade de pagamento, a classificação vigente e documentos contábeis atuais, como balanço, DRE e fluxo de caixa. Esses elementos não estão disponíveis no cenário demonstrativo." },
    { id: "cenarios", title: "Cenários de regularização e parcelamento", content: "Simulações de desconto, entrada e prazo aguardam a confirmação dos requisitos de cada modalidade. O sistema não aplica percentuais ou quantidade de parcelas automaticamente sem fundamento documentado e enquadramento do contribuinte." },
    { id: "judicial", title: "Situação judicial e garantias", content: "A análise de execuções, constrições e regularidade fiscal depende da leitura dos autos e das garantias existentes. Neste exemplo não foram obtidas peças judiciais, portanto não há recomendação de medida processual específica." },
    { id: "fundamentos", title: "Fundamentos e documentação de suporte", content: "Nenhuma norma ou edital foi validado para este cenário fictício. No parecer real, cada recomendação deverá indicar a fonte normativa, a data de conferência e a documentação que sustenta sua aplicação ao cliente." },
  ],
  pending: ["Relatório de capacidade de pagamento (CAPAG) e classificação vigente.", "Histórico de negociações, rescisões e eventuais impedimentos.", "Balanço, DRE e fluxo de caixa atualizados.", "Documentos dos processos judiciais e garantias existentes.", "Confirmação do edital e dos critérios de cada modalidade de regularização."],
  recommendations: ["Conferir as fontes oficiais e a composição de cada débito na mesma data de referência.", "Obter os documentos complementares antes de simular transação tributária.", "Submeter a estratégia de regularização à revisão da equipe técnica da FS."],
  conclusion: "Este diagnóstico demonstra a organização do passivo e a estrutura de análise da FS. A informação disponível não permite concluir o enquadramento em transação, estimar descontos ou afirmar regularidade fiscal. O parecer definitivo dependerá de fontes reais, documentos complementares e revisão técnica.",
});
