import { z } from "zod";
import { agentActor } from "@/lib/documentos/access";
import { documents,archiveDocument,auditDocument } from "@/lib/documentos/store";
import { boundedBody } from "@/lib/comercial/security";
import { isValidCnpj } from "@/lib/diagnostico/model";
export const runtime="nodejs";
export async function GET(request:Request){const actor=agentActor(request);if(!actor)return new Response(null,{status:401});const q=(new URL(request.url).searchParams.get('q')??'').trim();if(q.length<3||q.length>160)return Response.json({message:'Informe nome ou CNPJ.'},{status:422});const found=await documents(q,true);await auditDocument(actor,'search',null);return Response.json({documents:found.slice(0,100),total:found.length},{headers:{'Cache-Control':'no-store'}});}
const schema=z.object({externalId:z.string().min(1).max(150),cnpj:z.string().refine(isValidCnpj),company:z.string().min(1).max(200),name:z.string().min(1).max(160),kind:z.enum(['parecer','documento']),createdAt:z.string().datetime()});
export async function POST(request:Request){const actor=agentActor(request);if(!actor)return new Response(null,{status:401});try{const raw=await boundedBody(request,3*1024*1024+20000);const form=await new Response(raw,{headers:{'Content-Type':request.headers.get('content-type')??''}}).formData();const input=schema.parse(JSON.parse(String(form.get('metadata'))));const file=form.get('file');if(!(file instanceof File)||file.size>3*1024*1024)return new Response(null,{status:422});const content=Buffer.from(await file.arrayBuffer());if(content.subarray(0,5).toString()!=='%PDF-')return new Response(null,{status:422});input.name=input.name.replace(/[^\p{L}\p{N}._ -]/gu,'_');const id=await archiveDocument(input,content);await auditDocument(actor,'archive',id);return Response.json({id},{status:201});}catch(e){return Response.json({message:'Não foi possível arquivar o documento.'},{status:e instanceof Error&&e.message==='ARCHIVE_CONFLICT'?409:e instanceof Error&&e.message==='BODY_LIMIT'?413:422});}}
