"use client";
import Link from "next/link";
import { useEffect,useState,type FormEvent } from "react";
import { Search,FileText,ArrowUpRight,Download,FolderOpen,LoaderCircle } from "lucide-react";
import type { StoredDocument } from "@/lib/documentos/store";
import { formatCnpj } from "@/lib/diagnostico/model";
async function fetchDocuments(q:string,signal?:AbortSignal):Promise<{documents:StoredDocument[];total:number}>{const response=await fetch(`/api/documentos?q=${encodeURIComponent(q)}`,{signal,cache:'no-store'});if(response.status===401)window.location.assign('/login');if(!response.ok)throw new Error('library_unavailable');return response.json();}
export function DocumentLibrary({compact=false}:{compact?:boolean}){
 const [query,setQuery]=useState('');const [items,setItems]=useState<StoredDocument[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [total,setTotal]=useState(0);
 async function load(q:string){try{const data=await fetchDocuments(q);setItems(data.documents);setTotal(data.total);}catch{setError('Não foi possível carregar os documentos. Tente novamente.');}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();fetchDocuments('',controller.signal).then(data=>{setItems(data.documents);setTotal(data.total);setLoading(false);}).catch(()=>{if(!controller.signal.aborted){setError('Não foi possível carregar os documentos. Tente novamente.');setLoading(false);}});return()=>controller.abort();},[]);
 function search(e:FormEvent){e.preventDefault();setLoading(true);setError('');void load(query);}
 return <section className="diag-card fs-library"><div className="diag-card-title"><div><span className="diag-eyebrow">ACERVO COMPARTILHADO</span><h2>{compact?'Diagnósticos e documentos já elaborados':'Documentos da equipe'}</h2><p>Busque um parecer existente, sem realizar uma nova análise.</p></div><FolderOpen size={25}/></div><form onSubmit={search} className="fs-library-search"><label><Search size={18}/><input aria-label="Buscar documentos por empresa ou CNPJ" placeholder="Nome da empresa ou CNPJ" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="diag-button primary" disabled={loading}>Buscar</button></form>{error&&<p role="alert">{error}</p>}{loading?<p className="fs-library-empty"><LoaderCircle className="spin" size={18}/> Carregando acervo…</p>:!items.length?<div className="fs-library-empty"><FileText size={25}/><p>Nenhum documento encontrado. Pareceres anexados no Comercial e arquivados pelo agente aparecerão aqui.</p></div>:<div className="fs-library-list">{items.slice(0,compact&&!query?5:100).map(d=><article key={d.id}><div className="fs-library-icon"><FileText size={21}/></div><div className="fs-library-item"><strong>{d.company}</strong><p>{d.name}</p><small>{formatCnpj(d.cnpj)} · {new Date(d.createdAt).toLocaleDateString('pt-BR')} · {d.source}</small></div><div className="fs-library-actions"><a href={`/api/documentos/${d.id}`} target="_blank" rel="noopener noreferrer" aria-label={`Abrir ${d.name}`}>Abrir <ArrowUpRight size={16}/></a><a href={`/api/documentos/${d.id}?download=1`} aria-label={`Baixar ${d.name}`}><Download size={16}/></a></div></article>)}</div>}<div className="fs-library-foot"><span>{total} documento{total===1?'':'s'} encontrado{total===1?'':'s'}</span>{compact&&<Link href="/documentos">Ver acervo completo <ArrowUpRight size={14}/></Link>}</div></section>;
}
