"use client";
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {Building2,Search,RefreshCw,FileText,ArrowUpRight,Download,Paperclip,Globe,Clock3,CheckCircle2,Users,Info} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {stages,stageLabels,type Lead,type Attachment} from '@/lib/comercial/model';
import {formatCnpj} from '@/lib/diagnostico/model';
const date=(s:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(s));
const fileUrl=(lead:Lead,file:Attachment)=>`/api/comercial/leads/${lead.id}/anexos/${file.id}`;
export default function CommercialWorkspace(){
 const [leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState('dados'),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Attachment|null>(null);
 const load=useCallback(async()=>{try{const res=await fetch('/api/comercial/leads',{cache:'no-store'}),data=await res.json();if(!res.ok)throw Error(data.message||'Não foi possível carregar os contatos.');setLeads(data.leads);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha na conexão.');}finally{setLoading(false);}},[]);
 useEffect(()=>{const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},30000);return()=>{clearTimeout(initial);clearInterval(timer);};},[load]);
 const lead=leads.find(l=>l.id===selected),results=leads.filter(l=>`${l.event.company.name} ${l.event.company.cnpj} ${l.event.contact.name} ${l.event.contact.email}`.toLowerCase().includes(query.toLowerCase()));
 const replace=(updated:Lead)=>setLeads(old=>old.map(l=>l.id===updated.id?updated:l));
 async function move(stage:string){if(!lead)return;setBusy(true);try{const res=await fetch(`/api/comercial/leads/${lead.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage})}),data=await res.json();if(!res.ok)throw Error(data.message);replace(data.lead);setError('');}catch(e){setError(e instanceof Error?e.message:'Não foi possível mover o contato.');}finally{setBusy(false);}}
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!lead)return;const form=event.currentTarget;setBusy(true);try{const res=await fetch(`/api/comercial/leads/${lead.id}/anexos`,{method:'POST',body:new FormData(form)}),data=await res.json();if(!res.ok)throw Error(data.message);replace(data.lead);form.reset();setError('');}catch(e){setError(e instanceof Error?e.message:'Não foi possível anexar.');}finally{setBusy(false);}}
 const hasReport=(l:Lead)=>l.attachments.some(a=>a.kind==='parecer');
 return <div className="crm-workspace">
  <div className="crm-banner"><Globe size={19}/><div><strong>Do site para o Comercial</strong><p>Solicitações de diagnóstico chegam em Novos contatos. Abra um cartão para acompanhar o atendimento.</p></div><span>Entrada pelo site</span></div>
  <div className="crm-stats">{[{label:'Contatos recebidos',value:leads.length,icon:Users},{label:'Novos contatos',value:leads.filter(l=>l.stage===stages[0]).length,icon:Building2},{label:'Aguardando parecer',value:leads.filter(l=>!hasReport(l)).length,icon:Clock3},{label:'Com parecer anexado',value:leads.filter(hasReport).length,icon:CheckCircle2}].map(s=><div key={s.label}><s.icon size={20}/><span>{s.label}</span><strong>{s.value}</strong></div>)}</div>
  <div className="section-toolbar"><div><h2>Funil de oportunidades</h2><p>Contatos salvos, diagnósticos e documentos em um só lugar.</p></div><div className="toolbar-actions"><label className="crm-search"><Search size={17}/><input aria-label="Buscar contato" placeholder="Empresa, CNPJ ou responsável" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="diag-button" onClick={()=>{setLoading(true);void load();}} disabled={loading}><RefreshCw size={16}/>Atualizar</button></div></div>
  {error&&!lead&&<p role="alert" className="crm-error">{error}</p>}
  {loading&&<p role="status">Carregando contatos…</p>}
  <div className="kanban crm-kanban">{stages.map((stage,i)=><section className={`kanban-column ${['navy','blue','gold','green'][i]}`} key={stage}><div className="kanban-heading"><h3>{stageLabels[i]}<span>{results.filter(l=>l.stage===stage).length}</span></h3><small>{i===0?'Solicitações recebidas':'Acompanhamento da equipe'}</small></div>{results.filter(l=>l.stage===stage).map(l=><button className="opportunity crm-opportunity" key={l.id} onClick={()=>{setSelected(l.id);setTab('dados');setPreview(null);setError('');}}><span className="opportunity-service"><Globe size={12}/> Site · Diagnóstico</span><h4>{l.event.company.name}</h4><p>{formatCnpj(l.event.company.cnpj)}</p><p>{l.event.contact.name}</p><span className={`crm-status ${hasReport(l)?'ready':''}`}>{hasReport(l)?'Parecer disponível':'Aguardando análise'}</span><div><span><Clock3 size={12}/>{date(l.createdAt)}</span><span><Paperclip size={13}/>{l.attachments.length}</span></div></button>)}{!results.some(l=>l.stage===stage)&&<div className="kanban-empty">{query?'Nenhum contato corresponde à busca.':i===0?'As novas solicitações do site aparecerão aqui.':'Nenhum contato nesta etapa.'}</div>}</section>)}</div>
  <p className="crm-footnote"><Info size={15}/>A solicitação de atendimento não autoriza consultas fiscais. O diagnóstico depende das fontes e autorizações necessárias.</p>
  <Dialog open={!!lead} onOpenChange={open=>{if(!open){setSelected(null);setPreview(null);setError('');}}}><DialogContent className="crm-modal"><DialogHeader><span className="diag-eyebrow">COMERCIAL · CONTATO DO SITE</span><DialogTitle>{lead?.event.company.name}</DialogTitle><DialogDescription>{lead&&`${formatCnpj(lead.event.company.cnpj)} · Recebido em ${date(lead.createdAt)}`}</DialogDescription></DialogHeader>{lead&&<div className="crm-modal-body">
    <div className="crm-modal-top"><span className={`crm-status ${hasReport(lead)?'ready':''}`}>{hasReport(lead)?'Parecer disponível':'Aguardando análise'}</span><label>Etapa<select aria-label="Etapa do contato" disabled={busy} value={lead.stage} onChange={e=>void move(e.target.value)}>{stages.map((s,i)=><option key={s} value={s}>{stageLabels[i]}</option>)}</select></label></div>
    {error&&<p className="crm-error" role="alert">{error}</p>}
    <Tabs value={tab} onValueChange={value=>{setTab(value);setPreview(null);}}><TabsList className="crm-tabs"><TabsTrigger value="dados">Dados do contato</TabsTrigger><TabsTrigger value="diagnostico">Diagnóstico</TabsTrigger><TabsTrigger value="anexos">Anexos ({lead.attachments.length})</TabsTrigger></TabsList>
      <TabsContent value="dados"><div className="crm-fields">{[['Empresa',lead.event.company.name],['CNPJ',formatCnpj(lead.event.company.cnpj)],['Responsável',lead.event.contact.name],['E-mail',lead.event.contact.email],['WhatsApp',lead.event.contact.whatsapp],['Localização',[lead.event.company.city,lead.event.company.state].filter(Boolean).join(' / ')||'Não informada'],['Regime tributário',lead.event.company.tax_regime_label||'Não informado'],['Necessidade',lead.event.request.service_label]].map(([name,value])=><div key={name}><small>{name}</small><strong>{value}</strong></div>)}</div><div className="crm-message"><h3>Mensagem do cliente</h3><p>{lead.event.request.message||'Nenhuma observação informada.'}</p></div><div className="crm-consent"><CheckCircle2 size={16}/><p>Autorização para atendimento recebida em {date(lead.event.consent.received_at)}.<br/><small>{lead.event.consent.version} · Origem: site /diagnostico/</small></p></div><button className="diag-button primary" onClick={()=>setTab('diagnostico')}><FileText size={16}/>Abrir diagnóstico</button></TabsContent>
      <TabsContent value="diagnostico"><div className="crm-diagnostic-heading"><FileText size={25}/><div><h3>Diagnóstico tributário</h3><p>{hasReport(lead)?'Pareceres vinculados a esta empresa.':'Solicitação recebida. Ainda não há parecer vinculado a este contato.'}</p></div></div>{!hasReport(lead)&&<div className="crm-pending"><Clock3 size={24}/><h3>Aguardando análise</h3><p>Os débitos e o relatório serão exibidos após a consulta às fontes e a elaboração do parecer. Nenhum valor demonstrativo é atribuído a esta empresa.</p></div>}
        {lead.attachments.filter(a=>a.kind==='parecer').map(a=><Document key={a.id} lead={lead} file={a} onOpen={()=>setPreview(a)}/>)}
        {preview&&preview.kind==='parecer'&&<PdfPreview lead={lead} file={preview}/>}
        <form className="crm-upload" onSubmit={upload}><label htmlFor="parecer-file">Anexar parecer em PDF</label><input type="hidden" name="kind" value="parecer"/><input id="parecer-file" name="file" type="file" accept="application/pdf,.pdf" required disabled={busy}/><p>Até 3 MB. Confirme o CNPJ do documento antes de vinculá-lo.</p><button className="diag-button primary" disabled={busy}>{busy?'Salvando…':'Salvar parecer neste contato'}</button></form>
      </TabsContent>
      <TabsContent value="anexos"><h3 className="crm-attachments-title">Documentos deste contato</h3>{lead.attachments.map(a=><Document key={a.id} lead={lead} file={a} onOpen={()=>setPreview(a)}/>)}{!lead.attachments.length&&<p className="crm-pending">Nenhum arquivo anexado.</p>}{preview&&<PdfPreview lead={lead} file={preview}/>}<form className="crm-upload" onSubmit={upload}><label htmlFor="document-file">Adicionar documento de apoio</label><input type="hidden" name="kind" value="documento"/><input id="document-file" name="file" type="file" accept="application/pdf,.pdf" required disabled={busy}/><p>PDF de até 3 MB. Disponível somente neste contato.</p><button className="diag-button" disabled={busy}>{busy?'Salvando…':'Anexar documento'}</button></form></TabsContent>
    </Tabs>
  </div>}</DialogContent></Dialog>
 </div>;
}
function Document({lead,file,onOpen}:{lead:Lead;file:Attachment;onOpen:()=>void}){return <div className="crm-document"><FileText size={23}/><button onClick={onOpen}><strong>{file.name}</strong><small>{file.kind==='parecer'?'Parecer':'Documento'} · {Math.ceil(file.size/1024)} KB · {date(file.createdAt)}</small></button><a href={fileUrl(lead,file)+'?download=1'} aria-label={`Baixar ${file.name}`}><Download size={18}/></a></div>;}
function PdfPreview({lead,file}:{lead:Lead;file:Attachment}){return <div className="crm-pdf"><a href={fileUrl(lead,file)} target="_blank" rel="noopener noreferrer">Abrir PDF em outra aba para imprimir <ArrowUpRight size={15}/></a><iframe title={`PDF: ${file.name}`} src={fileUrl(lead,file)}/></div>;}
