import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {receiveDiagnostic} from '../lib/comercial/webhook';
import {saveEvent,listLeads,getLead,moveLead,addAttachment,getAttachment} from '../lib/comercial/store';
import type {DiagnosticEvent} from '../lib/comercial/model';
const directory=mkdtempSync(path.join(tmpdir(),'fs-crm-test-'));
before(()=>{process.env.FS_CRM_LOCAL_DIR=directory;delete process.env.FS_CRM_DATABASE_URL;delete process.env.DATABASE_URL;});
after(()=>rmSync(directory,{recursive:true,force:true}));
const env={FS_DIAGNOSTIC_WEBHOOK_TOKEN:'test-token',FS_DIAGNOSTIC_WEBHOOK_SECRET:'test-secret'};
function fixture():DiagnosticEvent{const date=new Date().toISOString();return {schema_version:'1.0',event:'diagnostic.requested',event_id:randomUUID(),occurred_at:date,source:{channel:'website',form:'diagnostico',page:'/diagnostico/'},funnel:{pipeline:'comercial',stage:'novos-contatos'},company:{name:'Empresa de homologação',cnpj:'11222333000181',city:'Goiânia',state:'GO',tax_regime:'real',tax_regime_label:'Lucro Real'},contact:{name:'Contato de teste',email:'teste@example.test',whatsapp:'62999999999'},request:{service:'diagnostico',service_label:'Diagnóstico tributário completo',message:'Dados fictícios'},consent:{accepted:true,version:'diagnostico-v1-2026-09-15',received_at:date,purpose:'Solicitação de diagnóstico e contato pela FS Soluções Tributárias'}};}
function request(event:DiagnosticEvent,overrides:Record<string,string>={}){const raw=JSON.stringify(event);return new Request('http://localhost:3100/api/webhooks/diagnostico',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${env.FS_DIAGNOSTIC_WEBHOOK_TOKEN}`,'Idempotency-Key':event.event_id,'X-FS-Event':event.event,'X-FS-Timestamp':event.occurred_at,'X-FS-Signature':`sha256=${createHmac('sha256',env.FS_DIAGNOSTIC_WEBHOOK_SECRET).update(`${event.occurred_at}.${raw}`).digest('hex')}`,...overrides},body:raw});}
test('webhook salva antes de confirmar, preserva conteúdo e deduplica com novo timestamp',async()=>{const event=fixture();const first=await receiveDiagnostic(request(event),saveEvent,env);assert.equal(first.status,201);const {lead_id}=await first.json();assert.deepEqual((await getLead(lead_id))?.event,event);const again={...event,occurred_at:new Date(Date.now()+1000).toISOString(),consent:{...event.consent,received_at:new Date(Date.now()+1000).toISOString()}};const second=await receiveDiagnostic(request(again),saveEvent,env);assert.equal(second.status,200);assert.equal((await second.json()).lead_id,lead_id);assert.equal((await listLeads()).filter(l=>l.event.event_id===event.event_id).length,1);const changed={...event,company:{...event.company,name:'Outro conteúdo'}};assert.equal((await receiveDiagnostic(request(changed),saveEvent,env)).status,409);});
test('rejeita token, assinatura, timestamp, CNPJ e etapa inválidos',async()=>{const event=fixture();const never=async()=>{assert.fail('não deve salvar');};assert.equal((await receiveDiagnostic(request(event,{'Authorization':'Bearer bad'}),never,env)).status,401);assert.equal((await receiveDiagnostic(request(event,{'X-FS-Signature':'sha256=bad'}),never,env)).status,401);assert.equal((await receiveDiagnostic(request({...event,occurred_at:'2020-01-01T00:00:00.000Z'}),never,env)).status,401);assert.equal((await receiveDiagnostic(request({...event,company:{...event.company,cnpj:'00000000000000'}}),never,env)).status,422);assert.equal((await receiveDiagnostic(request({...event,funnel:{pipeline:'outro',stage:'novos-contatos'}}),never,env)).status,422);});
test('não confirma recebimento quando armazenamento falha',async()=>{const res=await receiveDiagnostic(request(fixture()),async()=>{throw Error('unavailable');},env);assert.equal(res.status,503);assert.equal((await res.json()).received,undefined);});
test('anexo e etapa persistem no contato correto',async()=>{const a=await saveEvent(fixture()),b=await saveEvent(fixture());await moveLead(a.id,'qualificacao');assert.equal((await getLead(a.id))?.stage,'qualificacao');const pdf=Buffer.from('%PDF-1.7\nfixture');const updated=await addAttachment(a.id,'parecer.pdf','parecer',pdf);const id=updated!.attachments[0].id;assert.deepEqual((await getAttachment(a.id,id))?.content,pdf);assert.equal(await getAttachment(b.id,id),null);});
